#!/usr/bin/env bash

status=$(cat /sys/class/power_supply/BAT0/status)
capacity=$(cat /sys/class/power_supply/BAT0/capacity)

if [[ "$status" == "Charging" && "$capacity" -gt 80 ]]; then
  hyprctl notify 1 5000 "rgb(00ff00)" "Battery is full"
fi

if [[ "$status" == "Discharging" && "$capacity" -le 30 ]]; then
  hyprctl notify 1 5000 "rgb(ff0000)" "Battery low (30%). Please charge"
fi

echo "{\"percentage\": ${capacity}, \"status\": \"${status}\"}"
