#!/usr/bin/env bash

toggle() {
  if [[ $1 == "widgets-board" ]]; then toggle_widgets_board; fi
}

open() {
  if [[ $1 == "notification" ]]; then open_notification; fi
}

close() {
  if [[ $1 == "notification" ]]; then close_notification; fi
}

open_notification() {
  eww update reveal_notification=true
}

close_notification() {
  eww update reveal_notification=false
}

toggle_widgets_board() {
  state=$(eww get reveal_widgets_board)
  if [[ $state == "true" ]]; then
    eww update reveal_widgets_board=false
    sleep 0.5
    eww close widgets-board
  else
    eww open widgets-board
    eww update reveal_widgets_board=true
  fi
}


if [[ $1 == "toggle" ]]; then toggle $2; fi
if [[ $1 == "open" ]]; then open $2; fi
if [[ $1 == "close" ]]; then close $2; fi

