#!/usr/bin/env bash

handle() {
  app_name=$($1 | jq '.source')
  summary=$($1 | jq '.summary')

  echo "{ \"app_name\": "$app_name", \"summary\": "$summary" }"
}

open_notification() {
  eww update reveal_notification=true
}

tiramisu -j | while read -r line; do
  # handle "$line"
  echo $line
  open_notification
done
