#!/usr/bin/env bash

tiramisu -j | while read -r line; do
  echo $line
  $HOME/.config/eww/scripts/launcher toggle notification
  sleep 5
  $HOME/.config/eww/scripts/launcher toggle notification
done
